baseURL = "https://zak-hassan.github.io/"
languageCode = "en-us"
title = "Zak's Tech Notes"
theme = "ananke"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Publishing information about my development"
  facebook = ""
  twitter = "https://twitter.com/ZakHassan_YYZ"
  instagram = ""
  youtube = ""
  github = "https://github.com/zak-hassan"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/zak"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-washed-green"
  featured_image = "/images/sunset.png"
  recent_posts_number = 2
